# Generated by Django 3.0.8 on 2020-08-01 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True, verbose_name='ID в Telegram')),
                ('username', models.CharField(blank=True, help_text='Без @', max_length=74, null=True, verbose_name='Telegram username')),
                ('first_name', models.CharField(blank=True, max_length=74, null=True, verbose_name='Имя в ТГ')),
                ('last_name', models.CharField(blank=True, max_length=74, null=True, verbose_name='Фамилия в ТГ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь Телеграм',
                'verbose_name_plural': 'Пользователи Телеграм',
            },
        ),
    ]
